# Arquivo railway.yml

version: 1
frontend:
  builder: public
build:
  pre:
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
run:
  web: gunicorn gestao_web.wsgi
  backend: python manage.py run_huey
services:
  db:
    image: postgres
env:
  DATABASE_URL: postgres://postgres:fCkADNEmW7acYWT3aS44@containers-us-west-10.railway.app/postgresql_psycopg2