[runtime]
name = "python"
version = " 3.11.2"

[build]
command = "pip install -r requirements.txt"
command = "python manage.py collectstatic --noinput"

[run]
command = "python manage.py runserver 127.0.0.1:8000"
